# Generated by Django 5.2 on 2025-04-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('prazo', models.DateField()),
                ('numero_emenda', models.CharField(blank=True, max_length=50, null=True)),
                ('financiador', models.CharField(max_length=255)),
                ('conta_bancaria', models.CharField(max_length=50)),
                ('termo_fometo', models.TextField(blank=True, null=True)),
                ('detalhamento', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Custeio', 'Custeio'), ('Investimento', 'Investimento'), ('Aquisição de equipamento', 'Aquisição de equipamento'), ('Outros', 'Outros')], max_length=50)),
                ('status', models.CharField(choices=[('Em execução', 'Em Execucao'), ('Em prospecção', 'Em Prospecao'), ('Concluído', 'Concluido')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
