# Generated by Django 5.2 on 2025-04-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='data_entrada',
            new_name='data_termino',
        ),
    ]
