# Generated by Django 5.2 on 2025-04-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_data_entrada_projeto_data_termino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='termo_fometo',
            new_name='termo_fomento',
        ),
    ]
