# Generated by Django 5.2 on 2025-04-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_rename_termo_fometo_projeto_termo_fomento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='prazo',
        ),
    ]
